version: "3"
mysql:
  image: 'mysql:5.6'
  container_name: mysql_server
  environment:
    MYSQL_ROOT_PASSWORD: "123456"
  ports:
    - '3306:3306'
redis:
  build: ./redis/
  container_name: redis_server
  ports:
    - '6379:6379'
zookeeper:
  image: zookeeper:3.5.6
  restart: always
  hostname: zookeeper
  ports:
    - 2181:2181
